### ISSUE TITLE
When multiple solutions are present, only one arbitrary solution is valid

### ISSUE THREAD

**Issue by aimperiali** [liouh/picross#1]
When a cell is selected, the validity of that solution is checked against a single predetermined solution. This does not take into account scenarios where multiple solutions exist [See image below]

```
guess: function(x, y, guess) {
    var solution = this.get('solution')[x][y];
    ...

    ...
    if(solution === guess) {
        state[x][y] = guess;
    } else {
        state[x][y] = solution * -1;
        mistakes++;
    }
    ...

    ...
}
```

One solution would be to add an _else if_ statement between the _if_ and _else_ statements shown above. This _else if_ statement would check if the selected cell contradicts the rest of the board constraints. This solution is not enough on its own because the stored solution would have to be updated to reflect the new solution required.

Because of this, I would focus deriving an algorithm that can efficiently check if the current state of the board can reach a solved state or if there is bound to be a contradiction to the board constraints. This algorithm could then be used in place of the stored-solution-check noted above. I'll be giving this some more thought in my spare time.

![picross15x15_2](https://user-images.githubusercontent.com/33131548/39829331-1a8622d2-538c-11e8-8eb7-b1f071001de0.PNG)

**Comment by aimperiali** [comment]
To expand on the existing method, the following pseudocode would fall between the _if_ and _else_ statements noted above. This is intended to check the minimum number of cells required to know if the player is following a solution different valid solution for the given board constraints. This method makes the assumption that alternate solutions arise in the form of the corners of a rectangle that can be swapped around without violating the board constraints displayed.

```
User selects a cell (lets name it cell c0)
Cell is checked against the solution array



If cell is different than the corresponding cell in the original solution (called solution1):
    for every empty cell (called cA) in the same column (providing cA != c0):
        for every empty cell (called cB) in the same row as cA:
            remaining corner of this rectangle can be called cell cC
            create a temporary solution where the contents of cell cA are switched with cell c0 and the contents of cell cB are switched with cell cC (called solution2)
            check if solution2 has the same board constraints as solution1
            if solution2 is as valid as solution1:
                replace solution1 with solution 2
                mark cell c0 as correct
                break (stop checking)
            else:
                mark cell c0 as incorrect
                (keep checking)


```

**Comment by josephcsible** [comment]
FWIW, here's another board that exhibits this bug: 
![picross2](https://user-images.githubusercontent.com/16061266/43040930-2e8f0744-8d20-11e8-887a-79d9a58670fd.png)

**Comment by m-sterling** [comment]
I'd like to bump this thread to ask if either of you have found a solution for this?

I encountered a puzzle with this same bug (seed `1560713029296`) with four different solutions.

![Unsolved puzzle](https://user-images.githubusercontent.com/1697126/59568701-62bd5400-904c-11e9-8501-84c833d666bb.png)

Possible solutions include the following: [1](https://user-images.githubusercontent.com/1697126/59568706-77015100-904c-11e9-8a20-5c3ba26428c3.png), [2](https://user-images.githubusercontent.com/1697126/59568709-82547c80-904c-11e9-8248-ff70155c19f7.png), [3](https://user-images.githubusercontent.com/1697126/59568715-8ed8d500-904c-11e9-9d02-9accb185dc05.png), and [4](https://user-images.githubusercontent.com/1697126/59568718-98fad380-904c-11e9-8584-b7eb68bd61a9.png), but note that [only solution 3](https://user-images.githubusercontent.com/1697126/59568734-d0698000-904c-11e9-8302-bd563cf46daa.png) is recognized as the solution.

If I was more well-versed in JavaScript I might consider tackling this issue myself, but unfortunately that is not the case. 😄 However, I do propose a solution:

- removing the error autocorrection
- on every box fill/unfill action, check if the filled boxes satisfy the constraints of each line
- if so, mark it as solved

Of course, this then requires the "unmark" functionality, which hopefully doesn't seem like much. If I ever have time, I'll try to look at this with my limited JS knowledge.

**Comment by liouh** [comment]
I'm still surprised at the amount of traffic this 7-year-old project is getting. Apparently this version of the game is now the first hit for "picross" on Google 😮 Given the game's popularity, I was able to set aside a few hours today to look into a the multiple solutions problem.

I really liked the live-validating aspect of the original, and I tried to preserve it by regenerating the solutions board to match the constraints whenever a new "guess" was deemed incorrect. However, this is likely too slow for actual gameplay (runs in O(2^(NxM)) exponential time, where N and M are the board dimensions).

I ended up going with a variant of the suggestion by @kkirigaya -- removing the live-validation, and adding a button for the player to manually check à la https://www.puzzle-nonograms.com/. The seed generation hasn't changed, so you can test with your existing seeds.

**The new version is available online at http://liouh.com/picross2/**

Thanks for everyone that reported the issue, and enjoy!

**Comment by bertek41** [comment]
I think algorithm should check if its solvable because I got this:
![image](https://user-images.githubusercontent.com/20637793/147382690-127f2311-8219-473a-9c0f-43904d67df33.png)
and I can't even start. Seed is `1640425856979`
Tried http://a.teall.info/nonogram/ with `{"ver":[[4,1],[2],[1,2],[1,2,1],[1,1,2],[1,1,1,1,1],[3],[1,3],[1,1,1,1],[3,1,1]],"hor":[[2,1,1],[2,1,1,1],[1,1,1],[1,1,2],[1],[1,3,1],[1,1,1],[5],[1,1,2,1],[2,1,1]]}` and it couldn't solve either.

**Comment by liouh** [comment]
That seed is challenging but still solveable. It does require some trial and error, but the column with "5" and the row with "3" help narrow it down quite a bit. Make sure to enable show crossouts in the menu so you can see when the conditions are met.

**Comment by liouh** [comment]
Solution (spoilers): https://user-images.githubusercontent.com/1654183/147387037-b5f5ea25-04d2-4361-b560-cfb247f44d2c.png

**Comment by bertek41** [comment]
Yeah, I thought every step had to have a logical explanation. Column with "5" and row with "3" is a good start. However I couldn't finish I think I need to do some trial and error like you said. Thank you.
