### ISSUE TITLE
many solutions

### ISSUE THREAD

**Issue by TobiasNickel** [liouh/picross#5]
hi, I am a big fan of picross. to be honest, I played a while at picross.net, but that side is down now. So now I play this version for a few weeks. The biggest difference is that on a wrong click, it immediatly show an error. I really needed to get used to this, because i often just marked some helper fields and clear them afterwards. in this version I have to do this in my head.

while this mode of playing is likely for more advanced players, there is an other problem that I see. and that is that one game can have many solutions. I even implemented a picross solver using JS. in one of the generated games, my program found 257 solutions on a 10x10 grid. But the game is only accepting one of them.

I found when there are 4 - 8 solutions, I at least can find in my head all the solutions, the game might not blink in the end, but the player at least know the solutions. 

would you be interested in developing a version that filters games with too many solutions? maybe my picross solver can be of good use for that.

**Comment by liouh** [comment]
Try this version, which will validate solutions at the end: http://liouh.com/picross2/

More details in https://github.com/liouh/picross/issues/1
